<a href="https://colab.research.google.com/github/rameshawasthi/web-scraping/blob/main/web_scrapping_https_www_worldometers_info_coronavirus_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from bs4 import BeautifulSoup
import requests

url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup = requests.get(url)
soup

/usr/local/lib/python3.8/dist-packages/bs4/__init__.py:332: UserWarning: "https://www.worldometers.info/coronavirus/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  warnings.warn(

In [ ]:
soup = soup.text

In [ ]:
soup = BeautifulSoup(soup, "lxml")
soup

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID Live - Coronavirus Statistics - Worldometer</title>
<meta content="Live statistics and coronavirus news tracking the number of confirmed cases, recovered patients, tests, and death toll due to the COVID-19 coronavirus from Wuhan, China. Coronavirus counter with new cases, deaths, and number of tests per 1 Million population. Historical data and info. Daily charts, graphs, news and updates" name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- og image -->
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<!-- Bootstrap -->
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<!-- font awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<!-- tables
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js"></script>
 -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<!-- FREESTAR -->
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<!-- Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<!--
<script type="text/javascript" async=true>
(function() {
  var host = 'worldometers.info';
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://quantcast.mgr.consensu.org'
    .concat('/choice/', 'Pd9JxUkvV0m7q', '/', host, '/choice.js');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            event.source.postMessage(returnMsg, '*');
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
-->
<!-- End Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<!-- GA wm old (info) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<!-- GDPR consent -->
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/">Coronavirus</a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<!-- MAIN -->
<div class="container">
<!-- TOP AD -->
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- wm_top970 -->
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<!-- TOP AD -->
<!-- MAIN  -->
<!-- CENTER -->
<div class="row"> <div class="col-md-8">
<!-- *** CONTENT A *** -->
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<!-- charts -->
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: December 29, 2022, 09:14 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">663,614,057        </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,692,136</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>635,710,954</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<!-- START -->
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
                    Active Cases
                </span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">21,210,967</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">21,171,283</span> (<strong>99.8</strong>%)

                                    <div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">39,684</span> (<strong>0.2</strong>%)
                                    <div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>

In [ ]:
table = soup.table
table

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>121,262,081</td>
<td>+5,968</td>
<td>1,578,160</td>
<td>+28</td>
<td>116,064,929</td>
<td>+5,895</td>
<td>3,618,992</td>
<td>9,463</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>206,569,038</td>
<td>+296,874</td>
<td>1,511,056</td>
<td>+535</td>
<td>193,349,564</td>
<td>+90,025</td>
<td>11,708,418</td>
<td>11,311</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>242,702,348</td>
<td>+7,653</td>
<td>1,979,862</td>
<td>+71</td>
<td>236,773,224</td>
<td>+56,136</td>
<td>3,949,262</td>
<td>7,565</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>66,758,003</td>
<td>+3,145</td>
<td>1,341,406</td>
<td>+1</td>
<td>64,253,133</td>
<td>+23,085</td>
<td>1,163,464</td>
<td>10,341</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>13,582,848</td>
<td>+2,758</td>
<td>23,298</td>
<td>+24</td>
<td>13,232,703</td>
<td>+20</td>
<td>326,847</td>
<td>161</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,739,018</td>
<td></td>
<td>258,339</td>
<td></td>
<td>12,036,695</td>
<td></td>
<td>443,984</td>
<td>843</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>663,614,057</td>
<td>+316,398</td>
<td>6,692,136</td>
<td>+659</td>
<td>635,710,954</td>
<td>+175,161</td>
<td>21,210,967</td>
<td>39,684</td>
<td>85,135</td>
<td>858.5</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">102,407,740</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,117,194                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">99,367,089</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,923,457</td>
<td style="font-weight: bold; text-align:right">4,280</td>
<td style="font-weight: bold; text-align:right">305,873</td>
<td style="font-weight: bold; text-align:right">3,337</td>
<td style="font-weight: bold; text-align:right">1,151,491,932</td>
<td style="font-weight: bold; text-align:right">3,439,289</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>300</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">5,745</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,678,937</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">530,698                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,143,665</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">4,574</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">31,763</td>
<td style="font-weight: bold; text-align:right">377</td>
<td style="font-weight: bold; text-align:right">909,993,187</td>
<td style="font-weight: bold; text-align:right">646,931</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,651</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">39,245,937</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">161,715                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">38,169,715</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">914,507</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">598,402</td>
<td style="font-weight: bold; text-align:right">2,466</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>406</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">13,944</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">37,313,240</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">161,133                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,574,400</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+32,300</td>
<td style="text-align:right;font-weight:bold;">577,707</td>
<td style="font-weight: bold; text-align:right">1,406</td>
<td style="font-weight: bold; text-align:right">444,822</td>
<td style="font-weight: bold; text-align:right">1,921</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>521</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">6,887</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">36,275,146</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">693,604                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">34,891,300</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">690,242</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">168,445</td>
<td style="font-weight: bold; text-align:right">3,221</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>310</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,205</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">28,956,286</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+192,063</td>
<td style="font-weight: bold; text-align:right;">56,648                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+420</td>
<td style="font-weight: bold; text-align:right">21,073,394</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+19,417</td>
<td style="text-align:right;font-weight:bold;">7,826,244</td>
<td style="font-weight: bold; text-align:right">565</td>
<td style="font-weight: bold; text-align:right">230,572</td>
<td style="font-weight: bold; text-align:right">451</td>
<td style="font-weight: bold; text-align:right">86,237,109</td>
<td style="font-weight: bold; text-align:right">686,684</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>2,217</td><td>1</td>
<td style="font-weight: bold; text-align:right">1,529</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right">62,318</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">28,931,140</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+71,427</td>
<td style="font-weight: bold; text-align:right;">32,027                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+76</td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">27,696,531</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+54,250</td>
<td style="text-align:right;font-weight:bold;">1,202,582</td>
<td style="font-weight: bold; text-align:right">590</td>
<td style="font-weight: bold; text-align:right">563,631</td>
<td style="font-weight: bold; text-align:right">624</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>1,603</td><td>3</td>
<td style="font-weight: bold; text-align:right">1,392</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">23,428</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,021,606</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">183,936                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">24,401,205</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">436,465</td>
<td style="font-weight: bold; text-align:right">312</td>
<td style="font-weight: bold; text-align:right">415,208</td>
<td style="font-weight: bold; text-align:right">3,052</td>
<td style="font-weight: bold; text-align:right">261,751,623</td>
<td style="font-weight: bold; text-align:right">4,343,505</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>328</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">7,243</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,135,084</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">198,937                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,834,148</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,481</td>
<td style="text-align:right;font-weight:bold;">101,999</td>
<td style="font-weight: bold; text-align:right">146</td>
<td style="font-weight: bold; text-align:right">352,348</td>
<td style="font-weight: bold; text-align:right">2,904</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>344</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,489</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">21,787,172</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,146</td>
<td style="font-weight: bold; text-align:right;">393,604                                </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+56</td>
<td style="font-weight: bold; text-align:right">21,192,592</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+7,815</td>
<td style="text-align:right;font-weight:bold;">200,976</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">149,426</td>
<td style="font-weight: bold; text-align:right">2,700</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->

In [ ]:
tags = table.find_all('tr')
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>121,262,081</td>
 <td>+5,968</td>
 <td>1,578,160</td>
 <td>+28</td>
 <td>116,064,929</td>
 <td>+5,895</td>
 <td>3,618,992</td>
 <td>9,463</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>206,569,038</td>
 <td>+296,874</td>
 <td>1,511,056</td>
 <td>+535</td>
 <td>193,349,564</td>
 <td>+90,025</td>
 <td>11,708,418</td>
 <td>11,311</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>242,702,348</td>
 <td>+7,653</td>
 <td>1,979,862</td>
 <td>+71</td>
 <td>236,773,224</td>
 <td>+56,136</td>
 <td>3,949,262</td>
 <td>7,565</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>66,758,003</td>
 <td>+3,145</td>
 <td>1,341,406</td>
 <td>+1</td>
 <td>64,253,133</td>
 <td>+23,085</td>
 <td>1,163,464</td>
 <td>10,341</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>13,582,848</td>
 <td>+2,758</td>
 <td>23,298</td>
 <td>+24</td>
 <td>13,232,703</td>
 <td>+20</td>
 <td>326,847</td>
 <td>161</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,739,018</td>
 <td></td>
 <td>258,339</td>
 <td></td>
 <td>12,036,695</td>
 <td></td>
 <td>443,984</td>
 <td>843</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>663,614,057</td>
 <td>+316,398</td>
 <td>6,692,136</td>
 <td>+659</td>
 <td>635,710,954</td>
 <td>+175,161</td>
 <td>21,210,967</td>
 <td>39,684</td>
 <td>85,135</td>
 <td>858.5</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">102,407,740</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,117,194                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">99,367,089</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,923,457</td>
 <td style="font-weight: bold; text-align:right">4,280</td>
 <td style="font-weight: bold; text-align:right">305,873</td>
 <td style="font-weight: bold; text-align:right">3,337</td>
 <td style="font-weight: bold; text-align:right">1,151,491,932</td>
 <td style="font-weight: bold; text-align:right">3,439,289</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>300</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">5,745</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,678,937</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">530,698                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,143,665</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">4,574</td>
 <td style="font-weight: bold; text-align:right">698</td>
 <td style="font-weight: bold; text-align:right">31,763</td>
 <td style="font-weight: bold; text-align:right">377</td>
 <td style="font-weight: bold; text-align:right">909,993,187</td>
 <td style="font-weight: bold; text-align:right">646,931</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,651</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">39,245,937</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">161,715                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">38,169,715</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">914,507</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">598,402</td>
 <td style="font-weight: bold; text-align:right">2,466</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>406</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">13,944</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">37,313,240</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">161,133                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,574,400</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+32,300</td>
 <td style="text-align:right;font-weight:bold;">577,707</td>
 <td style="font-weight: bold; text-align:right">1,406</td>
 <td style="font-weight: bold; text-align:right">444,822</td>
 <td style="font-weight: bold; text-align:right">1,921</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>521</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">6,887</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">36,275,146</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">693,604                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">34,891,300</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">690,242</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">168,445</td>
 <td style="font-weight: bold; text-align:right">3,221</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>310</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,205</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">28,956,286</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+192,063</td>
 <td style="font-weight: bold; text-align:right;">56,648                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+420</td>
 <td style="font-weight: bold; text-align:right">21,073,394</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+19,417</td>
 <td style="text-align:right;font-weight:bold;">7,826,244</td>
 <td style="font-weight: bold; text-align:right">565</td>
 <td style="font-weight: bold; text-align:right">230,572</td>
 <td style="font-weight: bold; text-align:right">451</td>
 <td style="font-weight: bold; text-align:right">86,237,109</td>
 <td style="font-weight: bold; text-align:right">686,684</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>2,217</td><td>1</td>
 <td style="font-weight: bold; text-align:right">1,529</td>
 <td style="font-weight: bold; text-align:right">3</td>
 <td style="font-weight: bold; text-align:right">62,318</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">28,931,140</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+71,427</td>
 <td style="font-weight: bold; text-align:right;">32,027                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+76</td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">27,696,531</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+54,250</td>
 <td style="text-align:right;font-weight:bold;">1,202,582</td>
 <td style="font-weight: bold; text-align:right">590</td>
 <td style="font-weight: bold; text-align:right">563,631</td>
 <td style="font-weight: bold; text-align:right">624</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>1,603</td><td>3</td>
 <td style="font-weight: bold; text-align:right">1,392</td>
 <td style="font-weight: bold; text-align:right">1</td>
 <td style="font-weight: bold; text-align:right">23,428</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,021,606</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">183,936                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">24,401,205</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">436,465</td>
 <td style="font-weight: bold; text-align:right">312</td>
 <td style="font-weight: bold; text-align:right">415,208</td>
 <td style="font-weight: bold; text-align:right">3,052</td>
 <td style="font-weight: bold; text-align:right">261,751,623</td>
 <td style="font-weight: bold; text-align:right">4,343,505</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>328</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">7,243</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,135,084</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">198,937                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">23,834,148</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,481</td>
 <td style="text-align:right;font-weight:bold;">101,999</td>
 <td style="font-weight: bold; text-align:right">146</td>
 <td style="font-weight: bold; text-align:right">352,348</td>
 <td style="font-weight: bold; text-align:right">2,904</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>344</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,489</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">21,787,172</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+6,146</td>
 <td style="font-weight: bold; text-align:right;">393,604                                </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+56</td>
 <td style="font-weight: bold; text-align:right">21,192,592</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+7,815</td>
 <td style="text-align:right;font-weight:bold;">200,976</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">149,426</td>
 <td style="font-weight: bold; text-align:right">2,700</td>

In [ ]:
data = []
for tag in tags:
  x = tag.text
  x = x.split('\n')
  data.append(x[1:-1])

print(data)

[['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/', '1M pop', '', 'Population', 'Continent', '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl', 'New Cases/1M pop', 'New Deaths/1M pop', 'Active Cases/1M pop'], ['', '', 'North America', '', '121,262,081', '+5,968', '1,578,160', '+28', '116,064,929', '+5,895', '3,618,992', '9,463', '', '', '', '', '', 'North America', '', '', '', '', '', '', '', '', '', ''], ['', '', 'Asia', '', '206,569,038', '+296,874', '1,511,056', '+535', '193,349,564', '+90,025', '11,708,418', '11,311', '', '', '', '', '', 'Asia', '', '', '', '', '', '', '', '', '', ''], ['', '', 'Europe', '', '242,702,348', '+7,653', '1,979,862', '+71', '236,773,224', '+56,136', '3,949,262', '7,565', '', '', '', '', '', 'Europe', '', '', '', '', '', '', '', '', '', ''], ['', '', 'South America', '', '66,758,003', '+3,145', '1,341,406', '+1', '64,253,133', '+23,085', '1,163,464', '10,341', '', '', '', '', '', 'South America', '', '', '', '', '', '', '', '', '', ''], ['', '', 'Oceania', '', '13,582,848', '+2,758', '23,298', '+24', '13,232,703', '+20', '326,847', '161', '', '', '', '', '', 'Australia/Oceania', '', '', '', '', '', '', '', '', '', ''], ['', '', 'Africa', '', '12,739,018', '', '258,339', '', '12,036,695', '', '443,984', '843', '', '', '', '', '', 'Africa', '', '', '', '', '', '', '', '', '', ''], ['', '', '', '', '721', '', '15', '', '706', '', '0', '0', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], ['', 'World', '663,614,057', '+316,398', '6,692,136', '+659', '635,710,954', '+175,161', '21,210,967', '39,684', '85,135', '858.5', '', '', '', 'All', '', '', '', '', '', '', '', '', '', ''], ['1', 'USA', '102,407,740', '', '1,117,194                                ', '', '99,367,089', '', '1,923,457', '4,280', '305,873', '3,337', '1,151,491,932', '3,439,289', '334,805,269 ', 'North America', '', '33000', '', '', '5,745'], ['2', 'India', '44,678,937', '', '530,698                                ', '', '44,143,665', '', '4,574', '698', '31,763', '377', '909,993,187', '646,931', '1,406,631,776 ', 'Asia', '', '312,6512', '', '', '3'], ['3', 'France', '39,245,937', '', '161,715                                ', '', '38,169,715', '', '914,507', '869', '598,402', '2,466', '271,490,188', '4,139,547', '65,584,518 ', 'Europe', '', '24060', '', '', '13,944'], ['4', 'Germany', '37,313,240', '', '161,133                                ', '', '36,574,400', '+32,300', '577,707', '1,406', '444,822', '1,921', '122,332,384', '1,458,359', '83,883,596 ', 'Europe', '', '25211', '', '', '6,887'], ['5', 'Brazil', '36,275,146', '', '693,604                                ', '', '34,891,300', '', '690,242', '8,318', '168,445', '3,221', '63,776,166', '296,146', '215,353,593 ', 'South America', '', '63103', '', '', '3,205'], ['6', 'Japan', '28,956,286', '+192,063', '56,648                                ', '+420', '21,073,394', '+19,417', '7,826,244', '565', '230,572', '451', '86,237,109', '686,684', '125,584,838 ', 'Asia', '', '42,2171', '1,529', '3', '62,318'], ['7', 'S. Korea', '28,931,140', '+71,427', '32,027                                ', '+76', '27,696,531', '+54,250', '1,202,582', '590', '563,631', '624', '15,804,065', '307,892', '51,329,899 ', 'Asia', '', '21,6033', '1,392', '1', '23,428'], ['8', 'Italy', '25,021,606', '', '183,936                                ', '', '24,401,205', '', '436,465', '312', '415,208', '3,052', '261,751,623', '4,343,505', '60,262,770 ', 'Europe', '', '23280', '', '', '7,243'], ['9', 'UK', '24,135,084', '', '198,937                                ', '', '23,834,148', '+3,481', '101,999', '146', '352,348', '2,904', '522,526,476', '7,628,357', '68,497,907 ', 'Europe', '', '33440', '', '', '1,489'], ['10', 'Russia', '21,787,172', '+6,146', '393,604                                ', '+56', '21,192,592', '+7,815', '200,976', '2,300', '149,426', '2,700', '273,400,000', '1,875,095', '145,805,947 ', 'Europe', '', '73701', '42', '0.4', '1,378'], ['11', 'Turkey', '17,042,722', '', '101,492                                ', '', 'N/A', 'N/A', 'N/A', '', '199,186', '1,186', '162,743,369', '1,902,052', '85,561,976 ', 'Asia', '', '58431', '', '', '1,819'], ['12', 'Spain', '13,670,037', '', '116,899                                ', '', '13,466,158', '', '86,980', '339', '292,600', '2,502', '471,036,328', '10,082,298', '46,719,142 ', 'Europe', '', '34000', '', '', '1,862'], ['13', 'Vietnam', '11,524,779', '', '43,184                                ', '', '10,611,059', '', '870,536', '25', '116,467', '436', '85,826,548', '867,342', '98,953,541 ', 'Asia', '', '92,2911', '', '', '8,797'], ['14', 'Australia', '11,085,540', '+2,737', '16,964                                ', '+24', '10,869,679', '', '198,897', '106', '425,242', '651', '78,835,048', '3,024,116', '26,068,792 ', 'Australia/Oceania', '', '21,5370', '105', '0.9', '7,630'], ['15', 'Argentina', '9,891,139', '', '130,124                                ', '', '9,609,732', '', '151,283', '411', '214,977', '2,828', '35,716,069', '776,264', '46,010,234 ', 'South America', '', '53541', '', '', '3,288'], ['16', 'Taiwan', '8,794,212', '+27,955', '15,181                                ', '+36', '8,426,675', '+14,326', '352,356', '', '368,134', '635', '29,206,406', '1,222,609', '23,888,595 ', 'Asia', '', '31,5741', '1,170', '2', '14,750'], ['17', 'Netherlands', '8,565,849', '', '22,970                                ', '', '8,517,981', '+510', '24,898', '52', '497,683', '1,335', '25,984,435', '1,509,718', '17,211,447 ', 'Europe', '', '27491', '', '', '1,447'], ['18', 'Iran', '7,560,947', '', '144,677                                ', '', '7,336,033', '', '80,237', '76', '87,895', '1,682', '54,420,785', '632,632', '86,022,837 ', 'Asia', '', '115952', '', '', '933'], ['19', 'Mexico', '7,234,467', '+5,968', '331,099                                ', '+28', '6,468,257', '+3,784', '435,111', '4,798', '54,989', '2,517', '19,042,684', '144,742', '131,562,772 ', 'North America', '', '183977', '45', '0.2', '3,307'], ['20', 'Indonesia', '6,718,090', '', '160,574                                ', '', '6,542,791', '', '14,725', '2,771', '24,068', '575', '113,681,592', '407,265', '279,134,505 ', 'Asia', '', '421,7382', '', '', '53'], ['21', 'Poland', '6,366,622', '', '118,481                                ', '', '5,335,940', '', '912,201', '1,192', '168,698', '3,139', '37,960,795', '1,005,856', '37,739,785 ', 'Europe', '', '63191', '', '', '24,171'], ['22', 'Colombia', '6,338,339', '', '142,076                                ', '', '6,156,947', '', '39,316', '342', '123,044', '2,758', '36,951,507', '717,327', '51,512,762 ', 'South America', '', '83631', '', '', '763'], ['23', 'Austria', '5,691,663', '', '21,407                                ', '', '5,624,737', '', '45,519', '47', '627,754', '2,361', '204,391,491', '22,543,071', '9,066,710 ', 'Europe', '', '24240', '', '', '5,020'], ['24', 'Portugal', '5,554,058', '', '25,714                                ', '', '5,518,906', '+749', '9,438', '61', '547,707', '2,536', '45,801,053', '4,516,615', '10,140,570 ', 'Europe', '', '23940', '', '', '931'], ['25', 'Greece', '5,548,487', '', '34,779                                ', '', '5,500,066', '+6,821', '13,642', '115', '537,819', '3,371', '102,228,365', '9,909,078', '10,316,637 ', 'Europe', '', '22970', '', '', '1,322'], ['26', 'Ukraine', '5,354,738', '', '110,766                                ', '', '5,235,940', '+612', '8,032', '', '123,975', '2,564', '32,603,805', '754,855', '43,192,122 ', 'Europe', '', '83901', '', '', '186'], ['27', 'Malaysia', '5,024,902', '', '36,845                                ', '', '4,975,137', '', '12,920', '41', '151,439', '1,110', '67,093,829', '2,022,051', '33,181,072 ', 'Asia', '', '79010', '', '', '389'], ['28', 'Chile', '5,020,409', '', '63,076                                ', '', '4,947,224', '', '10,109', '107', '260,798', '3,277', '47,622,507', '2,473,871', '19,250,195 ', 'South America', '', '43050', '', '', '525'], ['29', 'DPRK', '4,772,813', '', '74                                ', '', '4,772,739', '', '0', '', '183,636', '3', '', '', '25,990,679 ', 'Asia', '', '5351,225', '', '', ''], ['30', 'Israel', '4,760,527', '', '12,023                                ', '', '4,736,531', '', '11,973', '57', '510,458', '1,289', '41,373,364', '4,436,346', '9,326,000 ', 'Asia', '', '27760', '', '', '1,284'], ['31', 'Thailand', '4,721,808', '', '33,594                                ', '', '4,649,509', '', '38,705', '1,496', '67,379', '479', '17,270,775', '246,450', '70,078,203 ', 'Asia', '', '152,0864', '', '', '552'], ['32', 'Belgium', '4,668,248', '', '33,228                                ', '', '4,603,036', '+817', '31,984', '82', '400,080', '2,848', '36,317,596', '3,112,507', '11,668,278 ', 'Europe', '', '23510', '', '', '2,741'], ['33', 'Czechia', '4,578,856', '+583', '42,106                                ', '+1', '4,530,321', '+186', '6,429', '57', '426,464', '3,922', '56,760,656', '5,286,560', '10,736,784 ', 'Europe', '', '22550', '54', '0.09', '599'], ['34', 'Canada', '4,475,268', '', '48,948                                ', '', '4,363,550', '+2,111', '62,770', '99', '116,579', '1,275', '66,343,123', '1,728,207', '38,388,419 ', 'North America', '', '97841', '', '', '1,635'], ['35', 'Peru', '4,451,074', '', '218,146                                ', '', '4,187,730', '+15,467', '45,198', '120', '132,141', '6,476', '37,298,236', '1,107,291', '33,684,208 ', 'South America', '', '81541', '', '', '1,342'], ['36', 'Switzerland', '4,365,574', '', '14,364                                ', '', '4,300,211', '+945', '50,999', '67', '497,579', '1,637', '23,194,219', '2,643,626', '8,773,637 ', 'Europe', '', '26110', '', '', '5,813'], ['37', 'Philippines', '4,062,659', '', '65,309                                ', '', '3,983,355', '', '13,995', '162', '36,110', '580', '33,989,511', '302,105', '112,508,994 ', 'Asia', '', '281,7233', '', '', '124'], ['38', 'South Africa', '4,048,580', '', '102,568                                ', '', '3,912,506', '', '33,506', '192', '66,637', '1,688', '26,473,049', '435,726', '60,756,135 ', 'Africa', '', '155922', '', '', '551'], ['39', 'Romania', '3,308,480', '', '67,374                                ', '', '3,234,288', '', '6,818', '114', '173,844', '3,540', '26,021,132', '1,367,278', '19,031,335 ', 'Europe', '', '62821', '', '', '358'], ['40', 'Denmark', '3,165,070', '', '7,747                                ', '', '3,148,109', '', '9,214', '22', '542,433', '1,328', '129,001,826', '22,108,472', '5,834,950 ', 'Europe', '', '27530', '', '', '1,579'], ['41', 'Sweden', '2,665,176', '', '21,595                                ', '', '2,608,142', '+882', '35,439', '42', '260,807', '2,113', '19,255,693', '1,884,308', '10,218,971 ', 'Europe', '', '44731', '', '', '3,468'], ['42', 'Hong Kong', '2,543,701', '', '11,621                                ', '', '2,039,485', '', '492,595', '49', '334,508', '1,528', '73,960,809', '9,726,184', '7,604,299 ', 'Asia', '', '36540', '', '', '64,778'], ['43', 'Iraq', '2,465,107', '', '25,373                                ', '', '2,439,079', '', '655', '21', '58,463', '602', '19,448,292', '461,243', '42,164,965 ', 'Asia', '', '171,6622', '', '', '16'], ['44', 'Serbia', '2,443,486', '', '17,505                                ', '', '2,412,015', '', '13,966', '17', '282,385', '2,023', '11,848,587', '1,369,301', '8,653,016 ', 'Europe', '', '44941', '', '', '1,614'], ['45', 'Singapore', '2,199,237', '', '1,711                                ', '', '2,124,969', '', '72,557', '4', '370,021', '288', '24,755,451', '4,165,098', '5,943,546 ', 'Asia', '', '33,4740', '', '', '12,208'], ['46', 'Hungary', '2,185,816', '', '48,495                                ', '', '2,123,750', '', '13,571', '16', '227,541', '5,048', '11,394,556', '1,186,160', '9,606,259 ', 'Europe', '', '41981', '', '', '1,413'], ['47', 'New Zealand', '2,094,354', '', '3,513                                ', '', '2,060,073', '', '30,768', '', '427,576', '717', '7,701,681', '1,572,348', '4,898,203 ', 'Australia/Oceania', '', '21,3941', '', '', '6,281'], ['48', 'Bangladesh', '2,037,067', '', '29,439                                ', '', '1,987,529', '', '20,099', '1,331', '12,134', '175', '15,140,368', '90,183', '167,885,689 ', 'Asia', '', '825,70311', '', '', '120'], ['49', 'Slovakia', '1,858,997', '+118', '20,817                                ', '+4', '1,836,873', '+141', '1,307', '40', '340,464', '3,813', '7,372,949', '1,350,309', '5,460,193 ', 'Europe', '', '32621', '22', '0.7', '239'], ['50', 'Georgia', '1,808,820', '', '16,897                                ', '', '1,776,548', '', '15,375', '', '455,767', '4,258', '16,920,079', '4,263,340', '3,968,738 ', 'Asia', '', '22350', '', '', '3,874'], ['51', 'Jordan', '1,746,997', '', '14,122                                ', '', '1,731,007', '', '1,868', '59', '169,597', '1,371', '17,201,885', '1,669,945', '10,300,869 ', 'Asia', '', '67291', '', '', '181'], ['52', 'Ireland', '1,687,668', '', '8,293                                ', '', '1,672,255', '+377', '7,120', '33', '336,176', '1,652', '12,901,532', '2,569,924', '5,020,199 ', 'Europe', '', '36050', '', '', '1,418'], ['53', 'Pakistan', '1,575,748', '+12', '30,636                                ', '', '1,538,689', '', '6,423', '19', '6,866', '133', '30,570,862', '133,213', '229,488,994 ', 'Asia', '', '1467,4918', '0.05', '', '28'], ['54', 'Norway', '1,474,517', '', '4,571                                ', '', '1,466,561', '', '3,385', '20', '267,541', '829', '11,002,430', '1,996,315', '5,511,370 ', 'Europe', '', '41,2061', '', '', '614'], ['55', 'Finland', '1,438,205', '', '7,933                                ', '', '1,406,325', '+622', '23,947', '21', '258,905', '1,428', '11,930,917', '2,147,795', '5,554,960 ', 'Europe', '', '47000', '', '', '4,311'], ['56', 'Kazakhstan', '1,402,543', '+263', '13,695                                ', '+1', '1,383,020', '', '5,828', '24', '73,030', '713', '11,575,012', '602,707', '19,205,043 ', 'Asia', '', '141,4022', '14', '0.05', '303'], ['57', 'Slovenia', '1,303,413', '', '6,998                                ', '', '1,272,410', '', '24,005', '22', '627,234', '3,368', '2,804,397', '1,349,543', '2,078,034 ', 'Europe', '', '22971', '', '', '11,552'], ['58', 'Bulgaria', '1,291,548', '', '38,097                                ', '', '1,249,488', '', '3,963', '35', '188,696', '5,566', '10,891,621', '1,591,273', '6,844,597 ', 'Europe', '', '51801', '', '', '579'], ['59', 'Lithuania', '1,287,398', '+443', '9,480                                ', '+3', '1,270,648', '+442', '7,270', '9', '483,674', '3,562', '10,309,757', '3,873,361', '2,661,708 ', 'Europe', '', '22810', '166', '1', '2,731'], ['60', 'Morocco', '1,271,440', '', '16,294                                ', '', '1,254,603', '', '543', '293', '33,660', '431', '12,845,318', '340,068', '37,772,756 ', 'Africa', '', '302,3183', '', '', '14'], ['61', 'Croatia', '1,262,465', '', '17,557                                ', '', '1,242,324', '', '2,584', '24', '311,007', '4,325', '5,419,106', '1,334,990', '4,059,286 ', 'Europe', '', '32311', '', '', '637'], ['62', 'Lebanon', '1,222,414', '', '10,745                                ', '', '1,087,587', '', '124,082', '74', '182,863', '1,607', '4,795,578', '717,380', '6,684,849 ', 'Asia', '', '56221', '', '', '18,562'], ['63', 'Guatemala', '1,199,343', '', '19,997                                ', '', '1,152,845', '', '26,501', '5', '64,536', '1,076', '6,526,284', '351,177', '18,584,039 ', 'North America', '', '159293', '', '', '1,426'], ['64', 'Costa Rica', '1,161,687', '', '9,072                                ', '', '860,711', '', '291,904', '52', '224,162', '1,751', '4,659,757', '899,158', '5,182,354 ', 'North America', '', '45711', '', '', '56,327'], ['65', 'Bolivia', '1,156,157', '+3,145', '22,291                                ', '+1', '1,099,992', '+883', '33,874', '220', '96,405', '1,859', '2,705,422', '225,590', '11,992,656 ', 'South America', '', '105384', '262', '0.08', '2,825'], ['66', 'Tunisia', '1,147,571', '', '29,284                                ', '', 'N/A', 'N/A', 'N/A', '44', '95,261', '2,431', '4,983,949', '413,721', '12,046,656 ', 'Africa', '', '104112', '', '', '688'], ['67', 'Cuba', '1,111,918', '', '8,530                                ', '', '1,103,181', '', '207', '23', '98,351', '754', '14,270,333', '1,262,230', '11,305,652 ', 'North America', '', '101,3251', '', '', '18'], ['68', 'UAE', '1,046,776', '', '2,348                                ', '', '1,029,199', '', '15,229', '', '103,828', '233', '197,888,076', '19,628,278', '10,081,785 ', 'Asia', '', '104,2940', '', '', '1,511'], ['69', 'Ecuador', '1,024,914', '', '35,940                                ', '', '988,974', '+6,735', '0', '759', '56,583', '1,984', '3,082,403', '170,173', '18,113,361 ', 'South America', '', '185046', '', '', ''], ['70', 'Panama', '1,023,778', '', '8,567                                ', '', '1,011,135', '', '4,076', '16', '230,220', '1,926', '7,385,118', '1,660,710', '4,446,964 ', 'North America', '', '45191', '', '', '917'], ['71', 'Uruguay', '1,011,988', '', '7,562                                ', '', '996,795', '', '7,631', '18', '289,469', '2,163', '6,114,822', '1,749,083', '3,496,016 ', 'South America', '', '34621', '', '', '2,183'], ['72', 'Mongolia', '1,007,266', '', '2,179                                ', '', '1,004,750', '+78', '337', '192', '298,177', '645', '4,030,048', '1,193,000', '3,378,078 ', 'Asia', '', '31,5501', '', '', '100'], ['73', 'Nepal', '1,000,975', '', '12,019                                ', '', '988,940', '', '16', '', '33,117', '398', '5,988,372', '198,123', '30,225,582 ', 'Asia', '', '302,5155', '', '', '0.5'], ['74', 'Belarus', '994,037', '', '7,118                                ', '', '985,592', '', '1,327', '', '105,381', '755', '13,646,641', '1,446,722', '9,432,800 ', 'Europe', '', '91,3251', '', '', '141'], ['75', 'Latvia', '973,466', '+363', '6,152                                ', '+7', '950,319', '', '16,995', '3', '526,529', '3,327', '7,766,325', '4,200,654', '1,848,837 ', 'Europe', '', '23010', '196', '4', '9,192'], ['76', 'Saudi Arabia', '826,927', '', '9,513                                ', '', '814,489', '', '2,925', '22', '23,070', '265', '44,931,128', '1,253,487', '35,844,909 ', 'Asia', '', '433,7681', '', '', '82'], ['77', 'Azerbaijan', '826,165', '', '10,008                                ', '', '815,641', '', '516', '', '80,209', '972', '7,425,687', '720,926', '10,300,205 ', 'Asia', '', '121,0291', '', '', '50'], ['78', 'Paraguay', '785,534', '', '19,666                                ', '', 'N/A', 'N/A', 'N/A', '7', '107,521', '2,692', '2,657,506', '363,751', '7,305,843 ', 'South America', '', '93713', '', '', '9,246'], ['79', 'Bahrain', '698,599', '', '1,539                                ', '', '696,397', '', '663', '12', '391,595', '863', '10,628,414', '5,957,688', '1,783,983 ', 'Asia', '', '31,1590', '', '', '372'], ['80', 'Sri Lanka', '671,875', '', '16,817                                ', '', '655,001', '', '57', '', '31,140', '779', '6,486,117', '300,619', '21,575,842 ', 'Asia', '', '321,2833', '', '', '3'], ['81', 'Kuwait', '662,747', '', '2,570                                ', '', '660,095', '', '82', '', '151,301', '587', '8,447,300', '1,928,464', '4,380,326 ', 'Asia', '', '71,7041', '', '', '19'], ['82', 'Dominican Republic', '650,990', '', '4,384                                ', '', '644,785', '', '1,821', '4', '58,879', '397', '3,740,928', '338,350', '11,056,370 ', 'North America', '', '172,5223', '', '', '165'], ['83', 'Myanmar', '633,639', '', '19,490                                ', '', '608,278', '', '5,871', '', '11,473', '353', '9,803,972', '177,521', '55,227,143 ', 'Asia', '', '872,8346', '', '', '106'], ['84', 'Cyprus', '628,509', '', '1,255 

In [ ]:
final_data = []
for j in data:
  if j[0] != '':
    final_data.append(j)

print(final_data)

[['#', 'Country,Other', 'TotalCases', 'NewCases', 'TotalDeaths', 'NewDeaths', 'TotalRecovered', 'NewRecovered', 'ActiveCases', 'Serious,Critical', 'Tot\xa0Cases/1M pop', 'Deaths/1M pop', 'TotalTests', 'Tests/', '1M pop', '', 'Population', 'Continent', '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl', 'New Cases/1M pop', 'New Deaths/1M pop', 'Active Cases/1M pop'], ['1', 'USA', '102,407,740', '', '1,117,194                                ', '', '99,367,089', '', '1,923,457', '4,280', '305,873', '3,337', '1,151,491,932', '3,439,289', '334,805,269 ', 'North America', '', '33000', '', '', '5,745'], ['2', 'India', '44,678,937', '', '530,698                                ', '', '44,143,665', '', '4,574', '698', '31,763', '377', '909,993,187', '646,931', '1,406,631,776 ', 'Asia', '', '312,6512', '', '', '3'], ['3', 'France', '39,245,937', '', '161,715                                ', '', '38,169,715', '', '914,507', '869', '598,402', '2,466', '271,490,188', '4,139,547', '65,584,518 ', 'Europe', '', '24060', '', '', '13,944'], ['4', 'Germany', '37,313,240', '', '161,133                                ', '', '36,574,400', '+32,300', '577,707', '1,406', '444,822', '1,921', '122,332,384', '1,458,359', '83,883,596 ', 'Europe', '', '25211', '', '', '6,887'], ['5', 'Brazil', '36,275,146', '', '693,604                                ', '', '34,891,300', '', '690,242', '8,318', '168,445', '3,221', '63,776,166', '296,146', '215,353,593 ', 'South America', '', '63103', '', '', '3,205'], ['6', 'Japan', '28,956,286', '+192,063', '56,648                                ', '+420', '21,073,394', '+19,417', '7,826,244', '565', '230,572', '451', '86,237,109', '686,684', '125,584,838 ', 'Asia', '', '42,2171', '1,529', '3', '62,318'], ['7', 'S. Korea', '28,931,140', '+71,427', '32,027                                ', '+76', '27,696,531', '+54,250', '1,202,582', '590', '563,631', '624', '15,804,065', '307,892', '51,329,899 ', 'Asia', '', '21,6033', '1,392', '1', '23,428'], ['8', 'Italy', '25,021,606', '', '183,936                                ', '', '24,401,205', '', '436,465', '312', '415,208', '3,052', '261,751,623', '4,343,505', '60,262,770 ', 'Europe', '', '23280', '', '', '7,243'], ['9', 'UK', '24,135,084', '', '198,937                                ', '', '23,834,148', '+3,481', '101,999', '146', '352,348', '2,904', '522,526,476', '7,628,357', '68,497,907 ', 'Europe', '', '33440', '', '', '1,489'], ['10', 'Russia', '21,787,172', '+6,146', '393,604                                ', '+56', '21,192,592', '+7,815', '200,976', '2,300', '149,426', '2,700', '273,400,000', '1,875,095', '145,805,947 ', 'Europe', '', '73701', '42', '0.4', '1,378'], ['11', 'Turkey', '17,042,722', '', '101,492                                ', '', 'N/A', 'N/A', 'N/A', '', '199,186', '1,186', '162,743,369', '1,902,052', '85,561,976 ', 'Asia', '', '58431', '', '', '1,819'], ['12', 'Spain', '13,670,037', '', '116,899                                ', '', '13,466,158', '', '86,980', '339', '292,600', '2,502', '471,036,328', '10,082,298', '46,719,142 ', 'Europe', '', '34000', '', '', '1,862'], ['13', 'Vietnam', '11,524,779', '', '43,184                                ', '', '10,611,059', '', '870,536', '25', '116,467', '436', '85,826,548', '867,342', '98,953,541 ', 'Asia', '', '92,2911', '', '', '8,797'], ['14', 'Australia', '11,085,540', '+2,737', '16,964                                ', '+24', '10,869,679', '', '198,897', '106', '425,242', '651', '78,835,048', '3,024,116', '26,068,792 ', 'Australia/Oceania', '', '21,5370', '105', '0.9', '7,630'], ['15', 'Argentina', '9,891,139', '', '130,124                                ', '', '9,609,732', '', '151,283', '411', '214,977', '2,828', '35,716,069', '776,264', '46,010,234 ', 'South America', '', '53541', '', '', '3,288'], ['16', 'Taiwan', '8,794,212', '+27,955', '15,181                                ', '+36', '8,426,675', '+14,326', '352,356', '', '368,134', '635', '29,206,406', '1,222,609', '23,888,595 ', 'Asia', '', '31,5741', '1,170', '2', '14,750'], ['17', 'Netherlands', '8,565,849', '', '22,970                                ', '', '8,517,981', '+510', '24,898', '52', '497,683', '1,335', '25,984,435', '1,509,718', '17,211,447 ', 'Europe', '', '27491', '', '', '1,447'], ['18', 'Iran', '7,560,947', '', '144,677                                ', '', '7,336,033', '', '80,237', '76', '87,895', '1,682', '54,420,785', '632,632', '86,022,837 ', 'Asia', '', '115952', '', '', '933'], ['19', 'Mexico', '7,234,467', '+5,968', '331,099                                ', '+28', '6,468,257', '+3,784', '435,111', '4,798', '54,989', '2,517', '19,042,684', '144,742', '131,562,772 ', 'North America', '', '183977', '45', '0.2', '3,307'], ['20', 'Indonesia', '6,718,090', '', '160,574                                ', '', '6,542,791', '', '14,725', '2,771', '24,068', '575', '113,681,592', '407,265', '279,134,505 ', 'Asia', '', '421,7382', '', '', '53'], ['21', 'Poland', '6,366,622', '', '118,481                                ', '', '5,335,940', '', '912,201', '1,192', '168,698', '3,139', '37,960,795', '1,005,856', '37,739,785 ', 'Europe', '', '63191', '', '', '24,171'], ['22', 'Colombia', '6,338,339', '', '142,076                                ', '', '6,156,947', '', '39,316', '342', '123,044', '2,758', '36,951,507', '717,327', '51,512,762 ', 'South America', '', '83631', '', '', '763'], ['23', 'Austria', '5,691,663', '', '21,407                                ', '', '5,624,737', '', '45,519', '47', '627,754', '2,361', '204,391,491', '22,543,071', '9,066,710 ', 'Europe', '', '24240', '', '', '5,020'], ['24', 'Portugal', '5,554,058', '', '25,714                                ', '', '5,518,906', '+749', '9,438', '61', '547,707', '2,536', '45,801,053', '4,516,615', '10,140,570 ', 'Europe', '', '23940', '', '', '931'], ['25', 'Greece', '5,548,487', '', '34,779                                ', '', '5,500,066', '+6,821', '13,642', '115', '537,819', '3,371', '102,228,365', '9,909,078', '10,316,637 ', 'Europe', '', '22970', '', '', '1,322'], ['26', 'Ukraine', '5,354,738', '', '110,766                                ', '', '5,235,940', '+612', '8,032', '', '123,975', '2,564', '32,603,805', '754,855', '43,192,122 ', 'Europe', '', '83901', '', '', '186'], ['27', 'Malaysia', '5,024,902', '', '36,845                                ', '', '4,975,137', '', '12,920', '41', '151,439', '1,110', '67,093,829', '2,022,051', '33,181,072 ', 'Asia', '', '79010', '', '', '389'], ['28', 'Chile', '5,020,409', '', '63,076                                ', '', '4,947,224', '', '10,109', '107', '260,798', '3,277', '47,622,507', '2,473,871', '19,250,195 ', 'South America', '', '43050', '', '', '525'], ['29', 'DPRK', '4,772,813', '', '74                                ', '', '4,772,739', '', '0', '', '183,636', '3', '', '', '25,990,679 ', 'Asia', '', '5351,225', '', '', ''], ['30', 'Israel', '4,760,527', '', '12,023                                ', '', '4,736,531', '', '11,973', '57', '510,458', '1,289', '41,373,364', '4,436,346', '9,326,000 ', 'Asia', '', '27760', '', '', '1,284'], ['31', 'Thailand', '4,721,808', '', '33,594                                ', '', '4,649,509', '', '38,705', '1,496', '67,379', '479', '17,270,775', '246,450', '70,078,203 ', 'Asia', '', '152,0864', '', '', '552'], ['32', 'Belgium', '4,668,248', '', '33,228                                ', '', '4,603,036', '+817', '31,984', '82', '400,080', '2,848', '36,317,596', '3,112,507', '11,668,278 ', 'Europe', '', '23510', '', '', '2,741'], ['33', 'Czechia', '4,578,856', '+583', '42,106                                ', '+1', '4,530,321', '+186', '6,429', '57', '426,464', '3,922', '56,760,656', '5,286,560', '10,736,784 ', 'Europe', '', '22550', '54', '0.09', '599'], ['34', 'Canada', '4,475,268', '', '48,948                                ', '', '4,363,550', '+2,111', '62,770', '99', '116,579', '1,275', '66,343,123', '1,728,207', '38,388,419 ', 'North America', '', '97841', '', '', '1,635'], ['35', 'Peru', '4,451,074', '', '218,146                                ', '', '4,187,730', '+15,467', '45,198', '120', '132,141', '6,476', '37,298,236', '1,107,291', '33,684,208 ', 'South America', '', '81541', '', '', '1,342'], ['36', 'Switzerland', '4,365,574', '', '14,364                                ', '', '4,300,211', '+945', '50,999', '67', '497,579', '1,637', '23,194,219', '2,643,626', '8,773,637 ', 'Europe', '', '26110', '', '', '5,813'], ['37', 'Philippines', '4,062,659', '', '65,309                                ', '', '3,983,355', '', '13,995', '162', '36,110', '580', '33,989,511', '302,105', '112,508,994 ', 'Asia', '', '281,7233', '', '', '124'], ['38', 'South Africa', '4,048,580', '', '102,568                                ', '', '3,912,506', '', '33,506', '192', '66,637', '1,688', '26,473,049', '435,726', '60,756,135 ', 'Africa', '', '155922', '', '', '551'], ['39', 'Romania', '3,308,480', '', '67,374                                ', '', '3,234,288', '', '6,818', '114', '173,844', '3,540', '26,021,132', '1,367,278', '19,031,335 ', 'Europe', '', '62821', '', '', '358'], ['40', 'Denmark', '3,165,070', '', '7,747                                ', '', '3,148,109', '', '9,214', '22', '542,433', '1,328', '129,001,826', '22,108,472', '5,834,950 ', 'Europe', '', '27530', '', '', '1,579'], ['41', 'Sweden', '2,665,176', '', '21,595                                ', '', '2,608,142', '+882', '35,439', '42', '260,807', '2,113', '19,255,693', '1,884,308', '10,218,971 ', 'Europe', '', '44731', '', '', '3,468'], ['42', 'Hong Kong', '2,543,701', '', '11,621                                ', '', '2,039,485', '', '492,595', '49', '334,508', '1,528', '73,960,809', '9,726,184', '7,604,299 ', 'Asia', '', '36540', '', '', '64,778'], ['43', 'Iraq', '2,465,107', '', '25,373                                ', '', '2,439,079', '', '655', '21', '58,463', '602', '19,448,292', '461,243', '42,164,965 ', 'Asia', '', '171,6622', '', '', '16'], ['44', 'Serbia', '2,443,486', '', '17,505                                ', '', '2,412,015', '', '13,966', '17', '282,385', '2,023', '11,848,587', '1,369,301', '8,653,016 ', 'Europe', '', '44941', '', '', '1,614'], ['45', 'Singapore', '2,199,237', '', '1,711                                ', '', '2,124,969', '', '72,557', '4', '370,021', '288', '24,755,451', '4,165,098', '5,943,546 ', 'Asia', '', '33,4740', '', '', '12,208'], ['46', 'Hungary', '2,185,816', '', '48,495                                ', '', '2,123,750', '', '13,571', '16', '227,541', '5,048', '11,394,556', '1,186,160', '9,606,259 ', 'Europe', '', '41981', '', '', '1,413'], ['47', 'New Zealand', '2,094,354', '', '3,513                                ', '', '2,060,073', '', '30,768', '', '427,576', '717', '7,701,681', '1,572,348', '4,898,203 ', 'Australia/Oceania', '', '21,3941', '', '', '6,281'], ['48', 'Bangladesh', '2,037,067', '', '29,439                                ', '', '1,987,529', '', '20,099', '1,331', '12,134', '175', '15,140,368', '90,183', '167,885,689 ', 'Asia', '', '825,70311', '', '', '120'], ['49', 'Slovakia', '1,858,997', '+118', '20,817                                ', '+4', '1,836,873', '+141', '1,307', '40', '340,464', '3,813', '7,372,949', '1,350,309', '5,460,193 ', 'Europe', '', '32621', '22', '0.7', '239'], ['50', 'Georgia', '1,808,820', '', '16,897                                ', '', '1,776,548', '', '15,375', '', '455,767', '4,258', '16,920,079', '4,263,340', '3,968,738 ', 'Asia', '', '22350', '', '', '3,874'], ['51', 'Jordan', '1,746,997', '', '14,122                                ', '', '1,731,007', '', '1,868', '59', '169,597', '1,371', '17,201,885', '1,669,945', '10,300,869 ', 'Asia', '', '67291', '', '', '181'], ['52', 'Ireland', '1,687,668', '', '8,293                                ', '', '1,672,255', '+377', '7,120', '33', '336,176', '1,652', '12,901,532', '2,569,924', '5,020,199 ', 'Europe', '', '36050', '', '', '1,418'], ['53', 'Pakistan', '1,575,748', '+12', '30,636                                ', '', '1,538,689', '', '6,423', '19', '6,866', '133', '30,570,862', '133,213', '229,488,994 ', 'Asia', '', '1467,4918', '0.05', '', '28'], ['54', 'Norway', '1,474,517', '', '4,571                                ', '', '1,466,561', '', '3,385', '20', '267,541', '829', '11,002,430', '1,996,315', '5,511,370 ', 'Europe', '', '41,2061', '', '', '614'], ['55', 'Finland', '1,438,205', '', '7,933                                ', '', '1,406,325', '+622', '23,947', '21', '258,905', '1,428', '11,930,917', '2,147,795', '5,554,960 ', 'Europe', '', '47000', '', '', '4,311'], ['56', 'Kazakhstan', '1,402,543', '+263', '13,695                                ', '+1', '1,383,020', '', '5,828', '24', '73,030', '713', '11,575,012', '602,707', '19,205,043 ', 'Asia', '', '141,4022', '14', '0.05', '303'], ['57', 'Slovenia', '1,303,413', '', '6,998                                ', '', '1,272,410', '', '24,005', '22', '627,234', '3,368', '2,804,397', '1,349,543', '2,078,034 ', 'Europe', '', '22971', '', '', '11,552'], ['58', 'Bulgaria', '1,291,548', '', '38,097                                ', '', '1,249,488', '', '3,963', '35', '188,696', '5,566', '10,891,621', '1,591,273', '6,844,597 ', 'Europe', '', '51801', '', '', '579'], ['59', 'Lithuania', '1,287,398', '+443', '9,480                                ', '+3', '1,270,648', '+442', '7,270', '9', '483,674', '3,562', '10,309,757', '3,873,361', '2,661,708 ', 'Europe', '', '22810', '166', '1', '2,731'], ['60', 'Morocco', '1,271,440', '', '16,294                                ', '', '1,254,603', '', '543', '293', '33,660', '431', '12,845,318', '340,068', '37,772,756 ', 'Africa', '', '302,3183', '', '', '14'], ['61', 'Croatia', '1,262,465', '', '17,557                                ', '', '1,242,324', '', '2,584', '24', '311,007', '4,325', '5,419,106', '1,334,990', '4,059,286 ', 'Europe', '', '32311', '', '', '637'], ['62', 'Lebanon', '1,222,414', '', '10,745                                ', '', '1,087,587', '', '124,082', '74', '182,863', '1,607', '4,795,578', '717,380', '6,684,849 ', 'Asia', '', '56221', '', '', '18,562'], ['63', 'Guatemala', '1,199,343', '', '19,997                                ', '', '1,152,845', '', '26,501', '5', '64,536', '1,076', '6,526,284', '351,177', '18,584,039 ', 'North America', '', '159293', '', '', '1,426'], ['64', 'Costa Rica', '1,161,687', '', '9,072                                ', '', '860,711', '', '291,904', '52', '224,162', '1,751', '4,659,757', '899,158', '5,182,354 ', 'North America', '', '45711', '', '', '56,327'], ['65', 'Bolivia', '1,156,157', '+3,145', '22,291                                ', '+1', '1,099,992', '+883', '33,874', '220', '96,405', '1,859', '2,705,422', '225,590', '11,992,656 ', 'South America', '', '105384', '262', '0.08', '2,825'], ['66', 'Tunisia', '1,147,571', '', '29,284                                ', '', 'N/A', 'N/A', 'N/A', '44', '95,261', '2,431', '4,983,949', '413,721', '12,046,656 ', 'Africa', '', '104112', '', '', '688'], ['67', 'Cuba', '1,111,918', '', '8,530                                ', '', '1,103,181', '', '207', '23', '98,351', '754', '14,270,333', '1,262,230', '11,305,652 ', 'North America', '', '101,3251', '', '', '18'], ['68', 'UAE', '1,046,776', '', '2,348                                ', '', '1,029,199', '', '15,229', '', '103,828', '233', '197,888,076', '19,628,278', '10,081,785 ', 'Asia', '', '104,2940', '', '', '1,511'], ['69', 'Ecuador', '1,024,914', '', '35,940                                ', '', '988,974', '+6,735', '0', '759', '56,583', '1,984', '3,082,403', '170,173', '18,113,361 ', 'South America', '', '185046', '', '', ''], ['70', 'Panama', '1,023,778', '', '8,567                                ', '', '1,011,135', '', '4,076', '16', '230,220', '1,926', '7,385,118', '1,660,710', '4,446,964 ', 'North America', '', '45191', '', '', '917'], ['71', 'Uruguay', '1,011,988', '', '7,562                                ', '', '996,795', '', '7,631', '18', '289,469', '2,163', '6,114,822', '1,749,083', '3,496,016 ', 'South America', '', '34621', '', '', '2,183'], ['72', 'Mongolia', '1,007,266', '', '2,179                                ', '', '1,004,750', '+78', '337', '192', '298,177', '645', '4,030,048', '1,193,000', '3,378,078 ', 'Asia', '', '31,5501', '', '', '100'], ['73', 'Nepal', '1,000,975', '', '12,019                                ', '', '988,940', '', '16', '', '33,117', '398', '5,988,372', '198,123', '30,225,582 ', 'Asia', '', '302,5155', '', '', '0.5'], ['74', 'Belarus', '994,037', '', '7,118                                ', '', '985,592', '', '1,327', '', '105,381', '755', '13,646,641', '1,446,722', '9,432,800 ', 'Europe', '', '91,3251', '', '', '141'], ['75', 'Latvia', '973,466', '+363', '6,152                                ', '+7', '950,319', '', '16,995', '3', '526,529', '3,327', '7,766,325', '4,200,654', '1,848,837 ', 'Europe', '', '23010', '196', '4', '9,192'], ['76', 'Saudi Arabia', '826,927', '', '9,513                                ', '', '814,489', '', '2,925', '22', '23,070', '265', '44,931,128', '1,253,487', '35,844,909 ', 'Asia', '', '433,7681', '', '', '82'], ['77', 'Azerbaijan', '826,165', '', '10,008                                ', '', '815,641', '', '516', '', '80,209', '972', '7,425,687', '720,926', '10,300,205 ', 'Asia', '', '121,0291', '', '', '50'], ['78', 'Paraguay', '785,534', '', '19,666                                ', '', 'N/A', 'N/A', 'N/A', '7', '107,521', '2,692', '2,657,506', '363,751', '7,305,843 ', 'South America', '', '93713', '', '', '9,246'], ['79', 'Bahrain', '698,599', '', '1,539                                ', '', '696,397', '', '663', '12', '391,595', '863', '10,628,414', '5,957,688', '1,783,983 ', 'Asia', '', '31,1590', '', '', '372'], ['80', 'Sri Lanka', '671,875', '', '16,817                                ', '', '655,001', '', '57', '', '31,140', '779', '6,486,117', '300,619', '21,575,842 ', 'Asia', '', '321,2833', '', '', '3'], ['81', 'Kuwait', '662,747', '', '2,570                                ', '', '660,095', '', '82', '', '151,301', '587', '8,447,300', '1,928,464', '4,380,326 ', 'Asia', '', '71,7041', '', '', '19'], ['82', 'Dominican Republic', '650,990', '', '4,384                                ', '', '644,785', '', '1,821', '4', '58,879', '397', '3,740,928', '338,350', '11,056,370 ', 'North America', '', '172,5223', '', '', '165'], ['83', 'Myanmar', '633,639', '', '19,490                                ', '', '608,278', '', '5,871', '', '11,473', '353', '9,803,972', '177,521', '55,227,143 ', 'Asia', '', '872,8346', '', '', '106'], ['84', 'Cyprus', '628,509', '', '1,255                                ', '', '616,993', '', '10,261', '60', '513,745', '1,026', '9,640,118', '7,879,860', '1,223,387 ', 'Asia', '', '29750', '', '', '8,387'], ['85', 'Palestine', '620,816', '', '5,404                                ', '', '614,962', '', '450', '17', '116,137', '1,011', '3,078,533', '575,907', '5,345,541 ', 'Asia', '', '99892', '', '', '84'], ['86', 'Estonia', '611,891', '', '2,854                                ', '', '524,990', '', '84,047', '11', '462,884', '2,159', '3,633,360', '2,748,568', '1,321,910 ', 'Europe', '', '24630', '', '', '63,580'], ['87', 'Moldova', '596,550', '', '11,933                                ', '', '504,142', '', '80,475', '49', '148,648', '2,973', '3,216,305', '801,437', '4,013,171 ', 'Europe', '', '73361', '', '', '20,053'], ['88', 'Venezuela', '550,219', '', '5,830                                ', '', '542,742', '', '1,647', '36', '18,800', '199', '3,359,014', '114,771', '29,266,991 ', 'South America', '', '535,0209', '', '', '56'], ['89', 'Egypt', '515,645', '', '24,613                                ', '', '442,182', '', '48,850', '122', '4,857', '232', '3,693,367', '34,792', '106,156,692 ', 'Africa', '', '2064,31329', '', '', '460'], ['90', 'Libya', '507,142', '', '6,437                                ', '', '500,661', '', '44', '', '72,030', '914', '2,483,446', '352,725', '7,040,745 ', 'Africa', '', '141,0943', '', '', '6'], ['91', 'Ethiopia', '497,671', 

In [ ]:
import csv
file = open('covid_data1.csv','w')
x = csv.writer(file)
for i in final_data:
  x.writerow(i)

In [ ]:
import pandas as pd
df = pd.read_csv('covid_data1.csv')
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,"102,407,740",NaN,"1,117,194",NaN,"99,367,089",NaN,"1,923,457","4,280",...,"1,151,491,932","3,439,289","334,805,269",North America,NaN,33000,NaN,NaN,"5,745",NaN
1,2,India,"44,678,937",NaN,"530,698",NaN,"44,143,665",NaN,"4,574",698,...,"909,993,187","646,931","1,406,631,776",Asia,NaN,"312,6512",NaN,NaN,3,NaN
2,3,France,"39,245,937",NaN,"161,715",NaN,"38,169,715",NaN,"914,507",869,...,"271,490,188","4,139,547","65,584,518",Europe,NaN,24060,NaN,NaN,"13,944",NaN
3,4,Germany,"37,313,240",NaN,"161,133",NaN,"36,574,400","+32,300","577,707","1,406",...,"122,332,384","1,458,359","83,883,596",Europe,NaN,25211,NaN,NaN,"6,887",NaN
4,5,Brazil,"36,275,146",NaN,"693,604",NaN,"34,891,300",NaN,"690,242","8,318",...,"63,776,166","296,146","215,353,593",South America,NaN,63103,NaN,NaN,"3,205",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193,194,Vanuatu,"11,990",NaN,14,NaN,"11,952",NaN,24,NaN,...,"24,976","77,606","321,832",Australia/Oceania,NaN,"2722,98813",NaN,NaN,75,NaN
194,195,Greenland,"11,971",NaN,21,NaN,"2,761",NaN,"9,189",4,...,"164,926","2,894,810","56,973",North America,NaN,"52,7130",NaN,NaN,"161,287",NaN
195,196,Yemen,"11,945",NaN,"2,159",NaN,"9,124",NaN,662,23,...,"329,592","10,579","31,154,867",Asia,NaN,"2,60814,43095",NaN,NaN,21,NaN
196,197,Caribbean Netherlands,"11,625",NaN,38,NaN,"10,476",NaN,"1,111",NaN,...,"30,126","1,130,559","26,647",North America,NaN,27011,NaN,NaN,"41,693",NaN
197,198,Sint Maarten,"10,964",NaN,89,NaN,"10,873",NaN,2,NaN,...,"62,056","1,411,454","43,966",North America,NaN,44941,NaN,NaN,45,NaN

In [ ]:
deaths = []
countries = list(df['Country,Other'][0:10])
TotalDeaths = list(df['TotalCases'][0:10])
for i in TotalDeaths:
  v = int(i.replace(',',''))
  deaths.append(v)

In [ ]:
import plotly.graph_objects as go

fig = go.Figure([go.Bar(x=countries, y=deaths)])
fig.show()

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Pie(labels=countries, values=deaths)])
fig.show()